version: '3'

services:
  reverse-proxy:
    restart: always
    image: traefik:v2.8
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - openmaptiles_conn
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*"
  nginx:
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=(Host(`africa.tiles.openplaceguide.org`,`a.africa.tiles.openplaceguide.org`,`b.africa.tiles.openplaceguide.org`,`c.africa.tiles.openplaceguide.org`))"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.service=nginx"
      - "traefik.http.routers.nginx.tls=true"
  tileserver-gl:
    restart: always
